// This file is auto-generated by BoxScript documentation service.
declare module "modules" {

	/** A module that provides logging functionality to box-scripts */
	interface logger {
		/**
		 * Logs an informational message with the given arguments
		 * @param {string} message - The log message
		 * @param {any[]} args - The log arguments
		 * @returns {void}
		 */
		Trace(message: string, ...args: any[]): void;
		/**
		 * Logs a debug message with the given arguments
		 * @param {string} message - The log message
		 * @param {any[]} args - The log arguments
		 * @returns {void}
		 */
		Debug(message: string, ...args: any[]): void;
		/**
		 * Logs an informational message with the given arguments
		 * @param {string} message - The log message
		 * @param {any[]} args - The log arguments
		 * @returns {void}
		 */
		Info(message: string, ...args: any[]): void;
		/**
		 * Logs a warning message with the given arguments
		 * @param {string} message - The log message
		 * @param {any[]} args - The log arguments
		 * @returns {void}
		 */
		Warning(message: string, ...args: any[]): void;
		/**
		 * Logs an error message with the given arguments
		 * @param {string} message - The log message
		 * @param {any[]} args - The log arguments
		 * @returns {void}
		 */
		Error(message: string, ...args: any[]): void;
		/**
		 * Logs a critical error message with the given arguments
		 * @param {string} message - The log message
		 * @param {any[]} args - The log arguments
		 * @returns {void}
		 */
		Critical(message: string, ...args: any[]): void;
	}

	/** A proxy for StreamReader */
	interface StreamReaderProxy {
		/**
		 * Reads a line from the stream reader
		 * @returns {string}
		 */
		ReadLine(): string;
		/**
		 * Reads a line from the stream reader asynchronously
		 * @returns {Promise<string>}
		 */
		ReadLineAsync(): Promise<string>;
		/**
		 * Reads all remaining content from the stream reader
		 * @returns {string}
		 */
		ReadToEnd(): string;
		/**
		 * Reads all remaining content from the stream reader asynchronously
		 * @returns {Promise<string>}
		 */
		ReadToEndAsync(): Promise<string>;
		/**
		 * Closes the stream reader, releasing any resources associated with it
		 * @returns {void}
		 */
		Close(): void;
		/**
		 * Disposes of the stream reader, releasing any resources associated with it
		 * @returns {void}
		 */
		Dispose(): void;
	}

	/** A proxy for StreamWriter */
	interface StreamWriterProxy {
		/**
		 * Writes the given value to the stream writer
		 * @param {string} value - The value to write
		 * @returns {void}
		 */
		Write(value: string): void;
		/**
		 * Writes the given value to the stream writer asynchronously
		 * @param {string} value - The value to write
		 * @returns {Promise<void>}
		 */
		WriteAsync(value: string): Promise<void>;
		/**
		 * Writes a line with the given value to the stream writer
		 * @param {string} value - The value to write
		 * @returns {void}
		 */
		WriteLine(value: string): void;
		/**
		 * Writes a line with the given value to the stream writer asynchronously
		 * @param {string} value - The value to write
		 * @returns {Promise<void>}
		 */
		WriteLineAsync(value: string): Promise<void>;
		/**
		 * Flushes the stream writer, ensuring all data is written to the underlying stream
		 * @returns {void}
		 */
		Flush(): void;
		/**
		 * Flushes the stream writer asynchronously, ensuring all data is written to the underlying stream
		 * @returns {Promise<void>}
		 */
		FlushAsync(): Promise<void>;
		/**
		 * Closes the stream writer, releasing any resources associated with it
		 * @returns {void}
		 */
		Close(): void;
		/**
		 * Disposes of the stream writer, releasing any resources associated with it
		 * @returns {void}
		 */
		Dispose(): void;
	}

	/** A module that provides file system related functionalities to box-scripts */
	interface file {
		/**
		 * Copies the given file to the destination
		 * @param {string} source - The source file
		 * @param {string} destination - The destination path
		 * @param {boolean} [overwrite] - Whether or not to overwrite the file
		 * @returns {void}
		 */
		Copy(source: string, destination: string, overwrite?: boolean): void;
		/**
		 * Moves the given file to the destination
		 * @param {string} source - The source file to move
		 * @param {string} destination - The destination path
		 * @param {boolean} [overwrite] - Whether or not to overwrite the file
		 * @returns {void}
		 */
		Move(source: string, destination: string, overwrite?: boolean): void;
		/**
		 * Checks if the given file exists
		 * @param {string} path - The file path
		 * @returns {boolean}
		 */
		Exists(path: string): boolean;
		/**
		 * Deletes the given file
		 * @param {string} path - The file path
		 * @returns {void}
		 */
		Delete(path: string): void;
		/**
		 * Appends the given text to the end of the file
		 * @param {string} path - The file path
		 * @param {string} content - The content
		 * @returns {void}
		 */
		Append(path: string, content: string): void;
		/**
		 * Writes the given content to the file, overwriting any existing content
		 * @param {string} path - The file path
		 * @param {string} content - The content
		 * @returns {void}
		 */
		Write(path: string, content: string): void;
		/**
		 * Gets the creation time of the given file
		 * @param {string} path - The file path
		 * @returns {Date}
		 */
		CreateTime(path: string): Date;
		/**
		 * Gets the last time the file was accessed
		 * @param {string} path - The file path
		 * @returns {Date}
		 */
		AccessTime(path: string): Date;
		/**
		 * Gets the last time the file was written to
		 * @param {string} path - The file path
		 * @returns {Date}
		 */
		WriteTime(path: string): Date;
		/**
		 * Opens a file for reading as a text stream
		 * @param {string} path - The file path
		 * @returns {StreamReaderProxy}
		 */
		OpenRead(path: string): StreamReaderProxy;
		/**
		 * Opens a file for writing as a text stream
		 * @param {string} path - The file path
		 * @returns {StreamWriterProxy}
		 */
		OpenWrite(path: string): StreamWriterProxy;
		/**
		 * Creates a new file at the specified path
		 * @param {string} path - The file path
		 * @returns {StreamWriterProxy}
		 */
		Create(path: string): StreamWriterProxy;
		/**
		 * Ensures a file is created at the given path
		 * @param {string} path - The file path
		 * @returns {void}
		 */
		Touch(path: string): void;
	}

	/** A module that provides JSON functionality to box-scripts */
	interface json {
		/**
		 * Serializes the given value to a JSON string.
		 * @param {any} value - The value
		 * @returns {string}
		 */
		Serialize(value: any): string;
		/**
		 * Deserializes the given JSON string to a JsValue object.
		 * @param {string} value - The value
		 * @returns {any}
		 */
		Deserialize(value: string): any;
	}

	/** Represents a query parameter for an HTTP request */
	interface QueryParam {
		/** The key of the request */
		Key?: string;
		/** The value of the request */
		Value?: string;
	}

	/** Represents a range of HTTP status codes */
	interface CodeRange {
		/** The minimum value */
		Min: number;
		/** The exclusive maximum value */
		Max: number;
	}

	/** The settings for the HTTP module */
	interface HttpSettings {
		/** The method of the settings */
		Method?: string;
		/** The URL of the request */
		Url?: string;
		/** The base URL for the request */
		BaseUrl?: string;
		/** The headers for the request */
		readonly Headers?: { [key: string]: string };
		/** The query parameters for the request */
		readonly QueryParams?: QueryParam[];
		/** The status codes to expect from the request - Any code in this list will not result in an error */
		readonly ExpectStatusCodes?: CodeRange[];
		/** Whether or not to log the download progress of the HTTP request */
		LogDownload: boolean;
		/** Whether or not to log the upload progress during the HTTP request */
		LogUpload: boolean;
		/**
		 * Sets the method of the HTTP request
		 * @param {string} method - The HTTP method
		 * @returns {HttpSettings}
		 */
		SetMethod(method: string): HttpSettings;
		/**
		 * Sets the URL of the HTTP request
		 * @param {string} url - The URL
		 * @returns {HttpSettings}
		 */
		SetUrl(url: string): HttpSettings;
		/**
		 * Sets the base URL for the HTTP request
		 * @param {string} url - The URL
		 * @returns {HttpSettings}
		 */
		SetBaseUrl(url: string): HttpSettings;
		/**
		 * Adds a query parameter to the HTTP request
		 * @param {string} key - The key of the query parameter
		 * @param {string} value - The value of the query parameter
		 * @returns {HttpSettings}
		 */
		AddParam(key: string, value: string): HttpSettings;
		/**
		 * Adds a header to the HTTP request
		 * @param {string} key - The key of the header
		 * @param {string} value - The value of the header
		 * @returns {HttpSettings}
		 */
		SetHeader(key: string, value: string): HttpSettings;
		/**
		 * Sets the body to a JSON object
		 * @param {any} body - The body to set
		 * @returns {HttpSettings}
		 */
		JsonBody(body: any): HttpSettings;
		/**
		 * Sets the body content to a file
		 * @param {string} path - The path of the file
		 * @param {string} [mpcName] - The name of the multi-part form content header for the file
		 * @returns {HttpSettings}
		 */
		FileBody(path: string, mpcName?: string): HttpSettings;
		/**
		 * Sets the timeout in seconds for the HTTP request
		 * @param {number} seconds - The number of seconds
		 * @returns {HttpSettings}
		 */
		SetTimeoutSeconds(seconds: number): HttpSettings;
		/**
		 * Clears the expected HTTP response codes
		 * @returns {HttpSettings}
		 */
		ClearExpectedCodes(): HttpSettings;
		/**
		 * Adds an expected HTTP response code or range of codes - <paramref name="max" /> is exclusive
		 * @param {number} min - The min code to expect
		 * @param {number} [max] - The optional max code to expect
		 * @returns {HttpSettings}
		 */
		ExpectCode(min: number, max?: number): HttpSettings;
		/**
		 * Sets whether or not to log the download progress during the HTTP request
		 * @param {boolean} log - Whether or not to log the download progress
		 * @param {number} [seconds] - How often to log the progress (in seconds)
		 * @returns {HttpSettings}
		 */
		LogDownloads(log: boolean, seconds?: number): HttpSettings;
		/**
		 * Sets whether or not to log the upload progress during the HTTP request
		 * @param {boolean} log - Whether or not to log the upload progress
		 * @param {number} [seconds] - How often to log the progress (in seconds)
		 * @returns {HttpSettings}
		 */
		LogUploads(log: boolean, seconds?: number): HttpSettings;
	}

	/** A class that holds the progress of an HTTP request. */
	interface HttpProgress {
		/** The amount of bytes uploaded */
		readonly UploadedMb: number;
		/** The percentage of the upload that has been completed */
		readonly UploadPercentage: number;
		/** The time it took to upload the data */
		readonly UploadTimeSeconds: number;
		/** Whether or not the upload has finished */
		readonly UploadFinished: boolean;
		/** The amount of bytes downloaded */
		readonly DownloadedMb: number;
		/** The percentage of the download that has been completed */
		readonly DownloadPercentage: number;
		/** The time it took to download the data */
		readonly DownloadTimeSeconds: number;
		/** Whether or not the download has finished */
		readonly DownloadFinished: boolean;
		/** The settings for the request */
		readonly Settings?: HttpSettings;
	}

	/** A wrapper for the results of an HTTP request */
	interface HttpResp {
		/** The URL of the request */
		readonly Url?: string;
		/** The response code */
		readonly Code: number;
		/** Whether or not the response status code is within the expected range. */
		readonly Valid: boolean;
		/** The response headers */
		readonly Headers?: { [key: string]: string };
		/** The progress of the request */
		readonly Progress?: HttpProgress;
		/**
		 * Throws an exception if the response status code is not in the expected range.
		 * @returns {Promise<void>}
		 */
		ThrowIfBad(): Promise<void>;
		/**
		 * Returns the response body as a JSON value
		 * @returns {Promise<any>}
		 */
		AsJson(): Promise<any>;
		/**
		 * Returns the response body as a string
		 * @returns {Promise<string>}
		 */
		AsString(): Promise<string>;
		/**
		 * Writes the response body to a file
		 * @param {string} path - The file path
		 * @returns {Promise<void>}
		 */
		ToFile(path: string): Promise<void>;
		/**
		 * 
		 * @returns {void}
		 */
		Dispose(): void;
	}

	/** A module that provides HTTP functionality to box-scripts */
	interface http {
		/**
		 * Creates an instance of the HTTP settings module
		 * @returns {HttpSettings}
		 */
		Settings(): HttpSettings;
		/**
		 * Sends an HTTP request with the given settings and returns the response message
		 * @param {HttpSettings} settings - The settings for the request
		 * @returns {Promise<HttpResp>}
		 */
		Send(settings: HttpSettings): Promise<HttpResp>;
		/**
		 * Sends an HTTP request and returns the JSON response
		 * @param {HttpSettings} settings - The settings for the request
		 * @returns {Promise<any>}
		 */
		SendJson(settings: HttpSettings): Promise<any>;
		/**
		 * Sends a GET request to the given URL
		 * @param {string} url - The URL of the request
		 * @param {HttpSettings} [settings] - The optional settings for the request
		 * @returns {Promise<HttpResp>}
		 */
		Get(url: string, settings?: HttpSettings): Promise<HttpResp>;
		/**
		 * Sends a GET request to the given URL and returns the JSON response
		 * @param {string} url - The URL of the request
		 * @param {HttpSettings} [settings] - The optional settings for the request
		 * @returns {Promise<any>}
		 */
		GetJson(url: string, settings?: HttpSettings): Promise<any>;
		/**
		 * Sends a GET request to the given URL
		 * @param {string} url - The URL of the request
		 * @param {HttpSettings} [settings] - The optional settings for the request
		 * @returns {Promise<HttpResp>}
		 */
		Delete(url: string, settings?: HttpSettings): Promise<HttpResp>;
		/**
		 * Sends a DELETE request to the given URL and returns the JSON response
		 * @param {string} url - The URL of the request
		 * @param {HttpSettings} [settings] - The optional settings for the request
		 * @returns {Promise<any>}
		 */
		DeleteJson(url: string, settings?: HttpSettings): Promise<any>;
		/**
		 * Sends a POST request to the given URL
		 * @param {string} url - The URL of the request
		 * @param {any} body - The body data of the request
		 * @param {HttpSettings} [settings] - The optional settings for the request
		 * @returns {Promise<HttpResp>}
		 */
		Post(url: string, body: any, settings?: HttpSettings): Promise<HttpResp>;
		/**
		 * Sends a POST request to the given URL and returns the JSON response
		 * @param {string} url - The URL of the request
		 * @param {any} body - The body data of the request
		 * @param {HttpSettings} [settings] - The optional settings for the request
		 * @returns {Promise<any>}
		 */
		PostJson(url: string, body: any, settings?: HttpSettings): Promise<any>;
		/**
		 * Sends a PUT request to the given URL
		 * @param {string} url - The URL of the request
		 * @param {any} body - The body data of the request
		 * @param {HttpSettings} [settings] - The optional settings for the request
		 * @returns {Promise<HttpResp>}
		 */
		Put(url: string, body: any, settings?: HttpSettings): Promise<HttpResp>;
		/**
		 * Sends a PUT request to the given URL
		 * @param {string} url - The URL of the request
		 * @param {any} body - The body data of the request
		 * @param {HttpSettings} [settings] - The optional settings for the request
		 * @returns {Promise<any>}
		 */
		PutJson(url: string, body: any, settings?: HttpSettings): Promise<any>;
	}

	/** A module that provides configuration functionality to box-scripts */
	interface config {
		/**
		 * Gets the value of the given configuration key
		 * @param {string} key - The configuration key
		 * @returns {string}
		 */
		Get(key: string): string;
	}
	export var logger: logger;
	export var file: file;
	export var json: json;
	export var http: http;
	export var config: config;
}
