<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>box-script</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\BoxScript.Documentation\BoxScript.Documentation.csproj" />
		<ProjectReference Include="..\BoxScript.Modules\BoxScript.Modules.csproj" />
		<ProjectReference Include="..\BoxScript.Services\BoxScript.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="./../global.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Examples\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
